project_name: steadybit-extension-host-windows
version: 2

git:
  ignore_tags:
    - steadybit-extension-host-windows-*

builds:
  - binary: extension-host-windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    goarch:
      - amd64
    flags:
      - -cover={{ if index .Env "BUILD_WITH_COVERAGE"  }}{{ .Env.BUILD_WITH_COVERAGE }}{{ else }}false{{ end }}
      - -covermode=atomic

archives:
  - name_template: "{{ .ProjectName }}_{{ .Arch }}"
    formats: ["zip"]

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-{{ .Timestamp }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
